owgw:
  nodeSelector:
    env: tests
  tolerations:
  - key: "tests"
    operator: "Exists"
    effect: "NoSchedule"

  postgresql:
    primary:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"
    readReplicas:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"

owsec:
  nodeSelector:
    env: tests
  tolerations:
  - key: "tests"
    operator: "Exists"
    effect: "NoSchedule"

  postgresql:
    primary:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"
    readReplicas:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"

owgwui:
  nodeSelector:
    env: tests
  tolerations:
  - key: "tests"
    operator: "Exists"
    effect: "NoSchedule"

owfms:
  nodeSelector:
    env: tests
  tolerations:
  - key: "tests"
    operator: "Exists"
    effect: "NoSchedule"

  postgresql:
    primary:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"
    readReplicas:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"

owprov:
  nodeSelector:
    env: tests
  tolerations:
  - key: "tests"
    operator: "Exists"
    effect: "NoSchedule"

  postgresql:
    primary:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"
    readReplicas:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"

owprovui:
  nodeSelector:
    env: tests
  tolerations:
  - key: "tests"
    operator: "Exists"
    effect: "NoSchedule"

owls:
  nodeSelector:
    env: tests
  tolerations:
  - key: "tests"
    operator: "Exists"
    effect: "NoSchedule"

  postgresql:
    primary:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"
    readReplicas:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"

owlsui:
  nodeSelector:
    env: tests
  tolerations:
  - key: "tests"
    operator: "Exists"
    effect: "NoSchedule"

owanalytics:
  nodeSelector:
    env: tests
  tolerations:
  - key: "tests"
    operator: "Exists"
    effect: "NoSchedule"
  postgresql:
    primary:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"
    readReplicas:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"

owsub:
  nodeSelector:
    env: tests
  tolerations:
  - key: "tests"
    operator: "Exists"
    effect: "NoSchedule"
  postgresql:
    primary:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"
    readReplicas:
      nodeSelector:
        env: tests
      tolerations:
      - key: "tests"
        operator: "Exists"
        effect: "NoSchedule"

owrrm:
  nodeSelector:
    env: tests
  tolerations:
  - key: "tests"
    operator: "Exists"
    effect: "NoSchedule"
  mysql:
    nodeSelector:
      env: tests
    tolerations:
    - key: "tests"
      operator: "Exists"
      effect: "NoSchedule"

kafka:
  nodeSelector:
    env: tests
  tolerations:
  - key: "tests"
    operator: "Exists"
    effect: "NoSchedule"
  zookeeper:
    nodeSelector:
      env: tests
    tolerations:
    - key: "tests"
      operator: "Exists"
      effect: "NoSchedule"

postgresql-ha:
  pgpool:
    nodeSelector:
      env: tests
    tolerations:
    - key: "tests"
      operator: "Exists"
      effect: "NoSchedule"
  postgresql:
    nodeSelector:
      env: tests
    tolerations:
    - key: "tests"
      operator: "Exists"
      effect: "NoSchedule"
